name: Azure Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install NPM packages
        run: npm install
        
      - name: Building the project...
        run: npm run build
      
      - name: Deploying
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'react-app1'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: './dist'
